var array = [3, 8, 6, 4, 7, 9];
var index = array.indexOf(8);
console.log(index);
console.log(array);
array.push(6);
console.log(array);
array.pop();
console.log(array);
array.shift();
console.log(array);
array.unshift(1);
console.log(array);
var array = [3, 8, 6, 4, 7, 9];
var lastElement = array.pop();
console.log(lastElement);var array = [3, 8, 6, 4, 7, 9];
array.push(10);
console.log(array);